### ISSUE TITLE
Header "typ": "JWT" should not be added automatically

### ISSUE THREAD

**Issue by svenms** [nowakowskir/php-jwt#2] opened 2021-01-18 15:03 UTC
Hello,

Thanks for your development.
Unfortunately, the classes add a default header "typ": "JWT", which breaks the API call.
This parameter should not be added by default.

Please fix this.

Best regards,

**Comment by nowakowskir** [comment] 2022-11-14 17:42
Duplicate of https://github.com/nowakowskir/php-jwt/issues/1

**Closed as completed** 2022-11-14 17:42 UTC
